apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identityapp.fullname" . }}
  labels:
    {{- include "identityapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "identityapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "identityapp.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "identityapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          env:
            - name: spring_datasource_url
              valueFrom:
                configMapKeyRef:
                  name: {{ include "identityapp.fullname" . }}
                  key: mysqlUrl
            - name: spring_datasource_driver_class_name
              value: com.mysql.cj.jdbc.Driver
            - name: spring_datasource_username
              valueFrom:
                configMapKeyRef:
                  name: {{ include "identityapp.fullname" . }}
                  key: mysqlUser
            - name: spring_datasource_password
              valueFrom:
                configMapKeyRef:
                  name: {{ include "identityapp.fullname" . }}
                  key: mysqlPass
            - name: spring.jpa.hibernate.naming.physical-strategy
              value: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            - name: identity.serverMetadata.issuer
              valueFrom:
                configMapKeyRef:
                  key: issuer
                  name: {{ include "identityapp.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
